### ISSUE TITLE
Release 1.0 to Maven Central

### ISSUE THREAD

**Issue by nebhale** [nebhale/JsonPath#5]
Release 1.0 to Maven Central via Sonatype's OSS Maven Repository.  Depends on the support added in #4 which is now complete.

**Comment by btiernay** [comment]
Looks like this was build with Java 7? Alas, I cannot use this since I'm stuck on Java 6 for various reasons. Is Java 7 a requirement?

**Comment by nebhale** [comment]
Yeah, I made the decision to build it against Java 7 as Java 6 has finally been EOL'd according to the [Java SE Support Roadmap](http://www.oracle.com/technetwork/java/eol-135779.html).  I'd be open to changing it back to 6 based on demand, but as I've see in #3 you won't be able to use this project, I'm going to hold off.  If you find yourself coming back in the future, feel free to open an issue for Java 6 support.

**Comment by btiernay** [comment]
Hi Ben,

I understand Java 6 is EOL, but a lot of folks are still stuck on it due to various contraints. For me it's because I'm using CDH4 which currently doesn't support it.

That being said, it is also possible to support different versions of artifacts using Maven classifiers.

With respect to the last point, I am still very much interested in using your library. Are you open to the idea of new additions to functionality?

**Comment by nebhale** [comment]
I'd definitely be up for ideas on new functionality.  Obviously I need to finish off the full JsonPath syntax, but beyond that I'm interested in anything you've got.

Since you're interested I'll get another release going with Java 6 support.  It'll probably be tomorrow before it'll be ready but I'll open an issue to track it.
